#! /bin/bash
oldPath=$PWD
cd `dirname $0`
root=$PWD
cd $oldPath
source $root/lib/shimport $root/lib
shimport color_scheme.shh
shimport basic_func.shh
shopt -s  expand_aliases
alias ls='ls --color'
alias ll='ls -l'
alias la='ls -la'

listAvailableTools(){
    setArgs $*
    checkArgs '$_funcArgsCnt = 0' "Too many arguments"
    checkArgs '-d $root/tools' "Can not locate directory for tools"
    toolsList=`ls $root/tools`
    if [ "x$toolsList" != x ]
    then
        RUNMSGL "-- The following tools are available:"
        WARNTL "$toolsList"
    else WARN "Can not find any available tools!"
    fi
}

printHelpInfo(){
    if [ $# = 0 ]
    then
        echo -n "-- "; RUNMSGN "help"; echo -n " print help information, "
        echo "use \"help toolname\" for tool's help"
        echo -n "-- "; RUNMSGN "list"; echo " list all the tools available."
        echo -n "-- "; RUNMSGN "exit"; echo " exit my-tools' minimal bash"
    else
        for toolName in $*
        do
            if [ -f $root/tools/$toolName ]
            then
                echo -n "-- "; RUNMSG "Help information for $toolName"
                $toolName -h
            else ERROR "No tool named as $toolName!"
            fi
        done
    fi
}

echo    "=============================================================="
RUNMSG  "            Welcome to a minimal bash for my-tools            "
WARNT   "                All right reserved by Rock Lee                "
echo    "=============================================================="
RUNMSGL "            [You may use help for help information]           "
export PATH=$root/tools:$PATH

while [ 1 ]
do
    WARNTN "my-tools"; echo -n ":"
    RUNMSGN "$PWD"; echo -n "$ "
    read -a commandLines
    firstCommand=${commandLines[0]}
    commandLines[0]=''
    case x$firstCommand in
    x) continue;;
    xlist) listAvailableTools ${commandLines[*]};;
    xhelp) printHelpInfo ${commandLines[*]};;
    xexit) exit ${commandLines[*]};;
    x*) eval "$firstCommand ${commandLines[*]}";;
    esac
done
