#! /bin/bash
oldPath=$PWD
root=`dirname $0`
cd $root
root=$PWD
cd $oldPath
source $root/../lib/shimport $root/../lib
shimport color_scheme.shh

convertFile(){
	cp $1 /tmp/vtt2txt.tmp
    fileName=`basename $1 | sed 's/\./ /' | awk '{print $1}'`
	RUNMSGL ">> Converting $1 to `dirname $1`/$fileName.txt"
	sed -i '1,3d' /tmp/vtt2txt.tmp
	sed -i '/-->/d' /tmp/vtt2txt.tmp
	sed -i 's/&gt;//g' /tmp/vtt2txt.tmp
	$root/../src/trans_tool /tmp/vtt2txt.tmp `dirname $1`/$fileName.txt
    if [ x$deleteFlag = x1 ]
    then rm $1
    fi
	RUNMSGL ">> $1 conversion finished"
}

if [[ x$1 =~ ^(x|x-h)$ ]]
then
    echo "Usage: vtt2txt [options] [file/directory]"
    echo "    This tool is used for format conversion from \"vtt\" to \"txt\""
    echo "    -d, delete original files after format conversion"
    exit 0
elif [ x$1 = x-d ]
then
    deleteFlag=1
    shift
elif [ -f $1 ]
then convertFile $1
elif [ -d $1 ]
then
    fileList=`find $1 -name "*.vtt"`
    for file in $fileList
    do convertFile $file
    done
else
    ERROR "No such file or directory!"
    exit 1
fi
